ae: Declare our stats activity
E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver
	com.aicp.extras.romstats.ReportingServiceManager:
	java.lang.IllegalArgumentException: Component class
	com.aicp.extras.romstats.AnonymousStats does not exist
	in com.aicp.extras

Change-Id: Id9f20a3bc81d35843a1b4758d3973dffe13d6d59